### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by Torone** [mpangrazzi/redis-subscribe-sse#4]
I'm just testing it with my app but I can not get messages from Redis...
Here is my code so far and on 'pmessage' I receive nothing while I should receive a message:

```
var subscribe = require('../lib');
  var redisURL = url.parse(process.env.REDISCLOUD_URL);

  var sse = subscribe({
    channels: ['channel1', 'channel2', 'channel3', 'channel4'],
    retry: 5000,
    host: redisURL.hostname,
    port: redisURL.port,
    password: redisURL.auth.split(":")[1],
    clientOptions: {
      ignore_subscribe_messages: true,
      no_ready_check: true
    }
  });

  req.socket.setTimeout(0);

  res.set({
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive'
  });

  sse.pipe(res).on('close', function() {
    sse.close();
  });

  sse.on('pmessage', function (pattern, channel, message) {
    // Nothing here...?!?
    res.flush();
  });
```

What I'm doing wrong?
Thansk

**Comment by mpangrazzi** [comment]
Hi!

I see you've closed this issue... Did you find the problem or you still need help?

**Comment by Torone** [comment]
Hi!

I found in your lib folder you push messages from there! So I just changed it to fit my needs.
In my case the API push crypted messages through Redis and before pushing it I need to encrypt those and also `flush()` otherwise nothing arrive to the client.
It will be nice, maybe, to make the methods onMessage and onPmessage public in order to let people access it and push their information to the server.

Thanks for your package by the way!
Have a nice one!

**Comment by mpangrazzi** [comment]
If you're talking about a "middleware" for doing some data transformations **before** sending an SSE event to the client (like encryption/decryption or addtional serialization/deserialization), yes, it could be implemented, but I have to think a bit about it because I don't see a common use case right now.

However, you're also free to fork this repo or send a pull request if you want :)
