### ISSUE TITLE
Edit message before push SSE

### ISSUE THREAD

**Issue by Torone** [mpangrazzi/redis-subscribe-sse#5]
It would be nice to have possibility to handle messages before sending it to the client.

**Comment by mpangrazzi** [comment]
Hi,

can you give me an example use case for that feature? BTW, I think it's easy to implement.

Thank you

**Comment by Torone** [comment]
Hi,

Most of the Companies use Redis passing crypt messages: API send a crypt message and a proxy server use to decrypt message before pushing the update to the client via SSE.
This is just one of use case, but handling a message coming from an API before send it to the final client would be really useful.

Thanks

**Comment by mpangrazzi** [comment]
That's a good point. I'll add this feature on refactoring TODO, I think it will be trivial to implement: basically, we have to call a sort of a _transform_ function before pushing messages to stream in `onMessage` and `onPmessage` methods.

**Comment by Torone** [comment]
You can even add a method for pushing to be used in a callback. If someone is interested in editing a message will, probably, use a method that return just the message and after another one to push. Otherwise the current feature will be used. Does it make sense?

**Comment by mpangrazzi** [comment]
Just to let you know: I'm currently working on v 1.0.0 which is a complete rewritten on the module. Progress is available [here](https://github.com/mpangrazzi/redis-subscribe-sse/issues/3) an I've planned to add the feature we've talked about.
